/**
 * accessRoutes.js  —  Hardened Access Code API
 * ─────────────────────────────────────────────────────────────────────────────
 * Routes:
 *   GET  /api/access/generate   Admin-only. Generates a secure Base32 code,
 *                               stores a bcrypt hash, logs the event.
 *   POST /api/access/verify     Public (rate-limited). Verifies a code against
 *                               the stored bcrypt hash. Logs every attempt.
 *   GET  /api/access/audit      Admin-only. Returns last 100 audit entries.
 *   GET  /api/access/status     Admin-only. Shows current active code metadata.
 *
 * Security layers:
 *   • Rate limiting (express-rate-limit) on verify (10 req/15min per IP)
 *   • Admin-JWT middleware on generate, audit, status
 *   • bcrypt comparison — never a plaintext DB query for verify
 *   • CodeAuditLog written for every generate and verify event
 */

const express       = require('express');
const router        = express.Router();
const rateLimit     = require('express-rate-limit');
const AccessCode    = require('../models/AccessCode');
const CodeAuditLog  = require('../models/CodeAuditLog');
const { protect, admin } = require('../middleware/authMiddleware');
const {
    generateCode,
    hashCode,
    verifyCode,
    auditLog,
    formatExpiry
} = require('../services/SecureCodeService');

// ─────────────────────────────────────────────────────────────────────────────
// Rate limiters
// ─────────────────────────────────────────────────────────────────────────────
const verifyLimiter = rateLimit({
    windowMs: 15 * 60 * 1000,   // 15-minute window
    max: 10,                     // max 10 verify attempts per IP
    standardHeaders: true,
    legacyHeaders:  false,
    validate: { trustProxy: false },
    message: { success: false, message: 'Too many verification attempts. Please try again in 15 minutes.' },
});

const generateLimiter = rateLimit({
    windowMs: 60 * 60 * 1000,   // 1-hour window
    max: 5,                      // max 5 generate calls per admin IP per hour
    standardHeaders: true,
    legacyHeaders:  false,
    validate: { trustProxy: false },
    message: { success: false, message: 'Too many code generation requests.' },
});

// ─────────────────────────────────────────────────────────────────────────────
// Helper: extract client IP
// ─────────────────────────────────────────────────────────────────────────────
function getClientIp(req) {
    return (req.headers['x-forwarded-for'] || '').split(',')[0].trim()
        || req.socket?.remoteAddress
        || 'unknown';
}

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/access/generate   —   Admin-only, rate-limited
// ─────────────────────────────────────────────────────────────────────────────
router.get('/generate', protect, admin, generateLimiter, async (req, res) => {
    try {
        const now = new Date();

        // 1. Check for an already-active code
        const existingActive = await AccessCode.findOne({ expiresAt: { $gt: now }, isActive: true });

        if (existingActive) {
            // Return existing code info (admin can see the plaintext, it's for admin eyes only)
            return res.status(200).json({
                message: 'Active code already exists',
                code: existingActive.code,
                expiresAt: existingActive.expiresAt,
                expiresIn: formatExpiry(existingActive.expiresAt),
                usageCount: existingActive.usageCount,
                generatedBy: existingActive.generatedBy,
                version: existingActive.version,
            });
        }

        // 2. Generate a new secure Base32 code
        const plainCode  = generateCode(8);       // e.g. "X7KR4MPN"
        const hashedCode = await hashCode(plainCode);

        // 3. Expire old codes before creating new one
        await AccessCode.updateMany(
            { isActive: true },
            { $set: { isActive: false } }
        );

        // 4. Persist the new code (plaintext + hash)
        const expiresAt = new Date(now.getTime() + 24 * 60 * 60 * 1000); // 24 hours
        const newCode = await AccessCode.create({
            code:        plainCode,
            codeHash:    hashedCode,
            isActive:    true,
            expiresAt,
            generatedBy: req.user.email,
            generatedAt: now,
        });

        // 5. Audit log
        await auditLog({
            event:     'GENERATE',
            codeId:    newCode._id,
            ip:        getClientIp(req),
            userAgent: req.headers['user-agent'],
            success:   true,
            meta:      { generatedBy: req.user.email, version: newCode.version },
        });

        console.log(`[VAULT] New Secure Access Code Generated by ${req.user.email}: ${plainCode}`);

        res.status(201).json({
            message:    'New secure access code generated',
            code:       plainCode,
            expiresAt,
            expiresIn:  formatExpiry(expiresAt),
            usageCount: 0,
            generatedBy: req.user.email,
            version:    newCode.version,
        });

    } catch (err) {
        console.error('[accessRoutes] /generate error:', err.message);
        res.status(500).json({ message: 'Code generation failed. Server error.' });
    }
});

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/access/verify   —   Public, rate-limited (10/15min per IP)
// ─────────────────────────────────────────────────────────────────────────────
router.post('/verify', verifyLimiter, async (req, res) => {
    const { code } = req.body;
    const clientIp = getClientIp(req);

    if (!code || typeof code !== 'string') {
        return res.status(400).json({ success: false, message: 'Access code is required.' });
    }

    try {
        const now = new Date();

        // 1. Fetch the single active code document
        const activeCode = await AccessCode.findOne({ isActive: true, expiresAt: { $gt: now } });

        if (!activeCode) {
            await auditLog({
                event:   'VERIFY_FAIL',
                ip:      clientIp,
                userAgent: req.headers['user-agent'],
                success: false,
                meta:    { reason: 'NO_ACTIVE_CODE', input: code.substring(0, 8) },
            });
            return res.status(400).json({ success: false, message: 'No active access code found. Contact admin.' });
        }

        // 2. bcrypt comparison (never a plaintext DB query)
        const isMatch = await verifyCode(code.trim(), activeCode.codeHash);

        if (!isMatch) {
            // Audit failed attempt
            await auditLog({
                event:   'VERIFY_FAIL',
                codeId:  activeCode._id,
                ip:      clientIp,
                userAgent: req.headers['user-agent'],
                success: false,
                meta:    { reason: 'WRONG_CODE' },
            });
            return res.status(400).json({ success: false, message: 'Invalid or expired access code.' });
        }

        // 3. Update usage statistics
        await AccessCode.findByIdAndUpdate(activeCode._id, {
            $inc: { usageCount: 1 },
            $set: { lastUsedAt: now, lastUsedIp: clientIp },
        });

        // 4. Audit successful verification
        await auditLog({
            event:   'VERIFY_SUCCESS',
            codeId:  activeCode._id,
            ip:      clientIp,
            userAgent: req.headers['user-agent'],
            success: true,
            meta:    { usageCount: activeCode.usageCount + 1 },
        });

        res.status(200).json({
            success: true,
            message: 'Code verified. Premium menu unlocked.',
            expiresAt: activeCode.expiresAt,
        });

    } catch (err) {
        console.error('[accessRoutes] /verify error:', err.message);
        res.status(500).json({ message: 'Verification failed. Server error.' });
    }
});

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/access/audit   —   Admin-only, last 100 events
// ─────────────────────────────────────────────────────────────────────────────
router.get('/audit', protect, admin, async (req, res) => {
    try {
        const logs = await CodeAuditLog
            .find()
            .sort({ createdAt: -1 })
            .limit(100)
            .lean();

        res.status(200).json({ count: logs.length, logs });
    } catch (err) {
        console.error('[accessRoutes] /audit error:', err.message);
        res.status(500).json({ message: 'Failed to fetch audit logs.' });
    }
});

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/access/status   —   Admin-only, current code metadata
// ─────────────────────────────────────────────────────────────────────────────
router.get('/status', protect, admin, async (req, res) => {
    try {
        const now  = new Date();
        const code = await AccessCode.findOne({ isActive: true, expiresAt: { $gt: now } })
            .select('-codeHash')  // Never expose the hash
            .lean();

        if (!code) {
            return res.status(200).json({ active: false, message: 'No active code. Generate one.' });
        }

        res.status(200).json({
            active:      true,
            code:        code.code,
            expiresAt:   code.expiresAt,
            expiresIn:   formatExpiry(code.expiresAt),
            usageCount:  code.usageCount,
            generatedBy: code.generatedBy,
            lastUsedAt:  code.lastUsedAt,
            version:     code.version,
        });
    } catch (err) {
        console.error('[accessRoutes] /status error:', err.message);
        res.status(500).json({ message: 'Failed to fetch code status.' });
    }
});

module.exports = router;
